# Generated by Django 6.0.1 on 2026-02-10 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_collection_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('display_type', models.CharField(choices=[('checkbox', 'Checkbox List'), ('color_swatch', 'Color Swatch'), ('radio', 'Radio Buttons'), ('dropdown', 'Dropdown Select')], default='checkbox', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_expanded_by_default', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FilterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('value', models.CharField(blank=True, max_length=100)),
                ('color_code', models.CharField(blank=True, max_length=7, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('filter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.filtertype')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('filter_type', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CategoryFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_filters', to='api.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_filters', to='api.subcategory')),
                ('filter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filtertype')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductFilterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filteroption')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_values', to='api.product')),
            ],
            options={
                'unique_together': {('product', 'filter_option')},
            },
        ),
    ]
