# Generated by Django 6.0.1 on 2026-02-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_filtertype_filteroption_categoryfilter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolor',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='image',
        ),
        migrations.AddField(
            model_name='productcolor',
            name='hex_code',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
