# Generated by Django 6.0.1 on 2026-02-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_dimensiontemplate_filteroption_icon_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstyle',
            name='icon_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
