# Generated by Django 6.0.1 on 2026-02-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_productstyle_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstyle',
            name='icon_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
