# Generated by Django 6.0.1 on 2026-02-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_productmattress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_info_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='returns_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
