# Generated by Django 6.0.1 on 2026-02-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_product_show_size_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmattress',
            name='enable_bunk_positions',
            field=models.BooleanField(default=False),
        ),
    ]
