# Generated by Django 6.0.1 on 2026-02-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_productmattress_enable_bunk_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimension_paragraph',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='productimage',
            name='color_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
