# Generated by Django 6.0.1 on 2026-02-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_product_dimension_paragraph_productimage_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_dimensions_table',
            field=models.BooleanField(default=True),
        ),
    ]
