# Generated by Django 6.0.1 on 2026-02-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_product_show_dimensions_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmattress',
            name='price_both',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productmattress',
            name='price_bottom',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productmattress',
            name='price_top',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
