# Generated by Django 6.0.1 on 2026-02-24 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_product_dimension_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('cta_text', models.CharField(default='Shop Now', max_length=120)),
                ('cta_link', models.CharField(blank=True, default='', max_length=1000)),
                ('image', models.URLField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_slides', to='api.category')),
            ],
            options={
                'ordering': ['sort_order', '-updated_at'],
            },
        ),
    ]
